---
title: "03_table3_multiple_alpha"
author: "randy"
date: "`r Sys.Date()`"
output:
  pdf_document: default
  html_document: default
---


```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = TRUE,
                  warnings = FALSE,
                  message = FALSE,
                  comment = "#>",
                  #results = "hide",
                  error = FALSE)

## clean the R environment
graphics.off()
rm(list = ls())
freshr::freshr()

## load packages
library(here, quietly = TRUE)
library(tidyverse, quietly = TRUE)

## check the directory for the file
# here::dr_here()
here::set_here()

## the figure or results should be saved 
# paste0("foldername/Sfilename_workingresult_", 
#.       Sys.Date(), ".filetype")
```



```{r "files"}
source("R/07_summarization.R")
## the R file below is the code for results
# source("02_table2_plmlmm_code.R")
file_location <- "results/result_alphas_2023-08-23/"
files <- list.files(path = "results/result_alphas_2023-08-23/", pattern = ".Rdata")
files
```


```{r "calculate_alpha", warning = FALSE}
alphas <- anchortime <- map_dfr(files, ~pulltime(file_location, .)) %>%
  mutate(term = rep(c("bias", "mse", "cov50", "cov80", "cov90"), 4))
```


```{r}
options(digits = 4)
# [1] "anchor_time_c(3, 6, 9, 12)_alpha_multiple_2023-08-24 13:09:38.Rdata"  
# [2] "anchor_time_c(5, 10, 15)_alpha_multiple_2023-08-23 21:34:49.Rdata"    
# [3] "anchor_time_c(6, 10, 11, 12)_alpha_multiple_2023-08-24 09:48:43.Rdata"
# [4] "anchor_time_c(6, 9, 12, 15)_alpha_multiple_2023-08-24 13:02:29.Rdata" 
# [5] "anchor_time_c(8, 10, 12, 14)_alpha_multiple_2023-08-21 13:57:11.Rdata"
# [6] "anchor_time_c(8, 10, 12)_alpha_multiple_2023-08-23 21:43:28.Rdata" 
bias <- anchortime %>%
  filter(term == "bias") %>% 
  unnest() %>%
  mutate(Time = c("t(3, 6, 9, 12)",
                  "t(4, 8, 12)",
                  "t(5, 10, 15)", 
                  "t(6, 10, 11, 12)")) %>%
  mutate(Time = factor(Time, levels = c("t(4, 8, 12)",
                                        "t(5, 10, 15)",
                                        "t(3, 6, 9, 12)", 
                                        "t(6, 10, 11, 12)"))) %>% 
  arrange(Time) %>%
  dplyr::select(-term) %>% 
  dplyr::select(Time, sgl_n, eld_n, mhl_n, 
                mhl_p0, mhl_p1, mhl_p2, mhl_p3, 
                mhl_p4, mhl_p5, mhl_p6, mhl_p7)

bias
```



```{r}
rmse <- anchortime %>%
  filter(term == "mse") %>% 
  unnest() %>%
  mutate(Time = c("t(3, 6, 9, 12)",
                  "t(4, 8, 12)",
                  "t(5, 10, 15)", 
                  "t(6, 10, 11, 12)")) %>%
  mutate(Time = factor(Time, levels = c("t(4, 8, 12)",
                                        "t(5, 10, 15)",
                                        "t(3, 6, 9, 12)", 
                                        "t(6, 10, 11, 12)"))) %>% 
  arrange(Time) %>%
  dplyr::select(-term) %>% 
  dplyr::select(Time, sgl_n, eld_n, mhl_n, 
                mhl_p0, mhl_p1, mhl_p2, mhl_p3, 
                mhl_p4, mhl_p5, mhl_p6, mhl_p7) %>%
  mutate_if(is.numeric, sqrt)

cov50 <- anchortime %>%
  filter(term == "cov50") %>%   
  unnest() %>%
  mutate(Time = c("t(3, 6, 9, 12)",
                  "t(4, 8, 12)",
                  "t(5, 10, 15)", 
                  "t(6, 10, 11, 12)")) %>%
  mutate(Time = factor(Time, levels = c("t(4, 8, 12)",
                                        "t(5, 10, 15)",
                                        "t(3, 6, 9, 12)", 
                                        "t(6, 10, 11, 12)"))) %>% 
  arrange(Time) %>%
  dplyr::select(-term) %>% 
  dplyr::select(Time, sgl_n, eld_n, mhl_n,
                mhl_p0, mhl_p1, mhl_p2, mhl_p3, 
                mhl_p4, mhl_p5, mhl_p6, mhl_p7)

cov80 <- anchortime %>%
  filter(term == "cov80") %>%   
  unnest() %>%
  mutate(Time = c("t(3, 6, 9, 12)",
                  "t(4, 8, 12)",
                  "t(5, 10, 15)", 
                  "t(6, 10, 11, 12)")) %>%
  mutate(Time = factor(Time, levels = c("t(4, 8, 12)",
                                        "t(5, 10, 15)",
                                        "t(3, 6, 9, 12)", 
                                        "t(6, 10, 11, 12)"))) %>% 
  arrange(Time) %>%
  dplyr::select(-term) %>% 
  dplyr::select(Time, sgl_n, eld_n, mhl_n, 
                mhl_p0, mhl_p1, mhl_p2, mhl_p3, 
                mhl_p4, mhl_p5, mhl_p6, mhl_p7)

cov90 <- anchortime %>%
  filter(term == "cov90") %>% 
  unnest() %>%
  mutate(Time = c("t(3, 6, 9, 12)",
                  "t(4, 8, 12)",
                  "t(5, 10, 15)", 
                  "t(6, 10, 11, 12)")) %>%
  mutate(Time = factor(Time, levels = c("t(4, 8, 12)",
                                        "t(5, 10, 15)",
                                        "t(3, 6, 9, 12)", 
                                        "t(6, 10, 11, 12)"))) %>% 
  arrange(Time) %>%
  dplyr::select(-term) %>% 
  dplyr::select(Time, sgl_n, eld_n, mhl_n,
                mhl_p0, mhl_p1, mhl_p2, mhl_p3, 
                mhl_p4, mhl_p5, mhl_p6, mhl_p7)
```

```{r}
bias
rmse 
cov50
cov80
cov90
```


## saving the files as .tex

```{r}
library(xtable)

# xtable(bias, type = "latex", 
#        file = "/figure/S03_multiple_alpha_060_095_bias_20230822.tex")
# xtable(rmse, type = "latex", 
#        file = "/figure/S03_multiple_alpha_060_095_mse_20230822.tex")
# xtable(cov50, type = "latex", 
#        file = "/figure/S03_multiple_alpha_060_095_cov50_20230822.tex")
# xtable(cov80, type = "latex", 
#        file = "/figure/S03_multiple_alpha_060_095_cov80_20230822.tex")
# xtable(cov90, type = "latex", 
#        file = "/figure/S03_multiple_alpha_060_095_cov90_20230822.tex")

print(xtable(bias, type = "latex"), 
      file = paste0("figure/S03_multiple_alpha_060_095_bias_", Sys.Date(), ".tex"))
print(xtable(rmse, type = "latex"), 
      file = paste0("figure/S03_multiple_alpha_060_095_rmse_", Sys.Date(), ".tex"))
print(xtable(cov50, type = "latex"), 
      file = paste0("figure/S03_multiple_alpha_060_095_cov50_", Sys.Date(), ".tex"))
print(xtable(cov80, type = "latex"), 
      file = paste0("figure/S03_multiple_alpha_060_095_cov80_", Sys.Date(), ".tex"))
print(xtable(cov90, type = "latex"), 
      file = paste0("figure/S03_multiple_alpha_060_095_cov90_", Sys.Date(), ".tex"))
```



