---
title: "06_figure3_small_simulation"
author: "randy"
date: "`r Sys.Date()`"
output:
  pdf_document: default
  html_document: default
---


The simulation study with 500 samples and 400 in training set and 100 in testing set

```{r setup, include=FALSE}
# knitr::opts_chunk$set(echo = TRUE,
#                       warnings = FALSE,
#                       message = FALSE,
#                       comment = "#>",
#                       #results = "hide",
#                       digits = 4,
#                       error = FALSE)

## clean the R environment
graphics.off()
rm(list = ls())
freshr::freshr()

## load packages
library(here, quietly = TRUE)
library(tidyverse, quietly = TRUE)
library(gtsummary, quietly = TRUE)
library(flextable, quietly = TRUE)

## check the directory for the file
# here::dr_here()
here::set_here()

## the figure or results should be saved 
# paste0("foldername/Sfilename_workingresult_", 
#.       Sys.Date(), ".filetype")
```


```{r eval=FALSE, include=FALSE}
## 7.1 meanout -----------------------------------------------------------------
meanout <- function(dataset,
                    term = c("bias", "mse", "coverage50",
                             "coverage80", "coverage90"),
                    ...){
  result <- dataset %>%
    map("centiles_observed")
  result <- keep(result, ~ length(.x) > 1) %>%
    map(~mutate(., bias = abs(`50` - actual),
                 coverage50 = ifelse(actual >= `25` & actual <= `75`, 1, 0),
                 coverage80 = ifelse(actual >= `10` & actual <= `90`, 1, 0),
                 coverage90 = ifelse(actual >= `5` & actual <= `95`, 1, 0)))
  if (term != "mse") {
    result <- result %>%
      map(term) %>%
      map(~mean(., na.rm = TRUE)) %>%
      unlist() %>%
      mean()
  } else {
    result <- result %>%
      map(~.$bias ^2) %>%
      map(~mean(., na.rm = TRUE)) %>%
      unlist() %>%
      mean()
  }
  return(result)
}

## 7.2 meanout -----------------------------------------------------------------
meanall <- function(dataset,
                    ...){
  bias <- meanout(dataset, "bias")
  mse <- meanout(dataset, "mse")
  cov50 <- meanout(dataset, "coverage50")
  cov80 <- meanout(dataset, "coverage80")
  cov90 <- meanout(dataset, "coverage90")

  return(list(bias = bias,
              mse = mse,
              cov50 = cov50,
              cov80 = cov80,
              cov90 = cov90))
}


pull_simulation <- function(location,
                    filename) {
  load(paste0(location, filename))

  ## eld_n test {{{-------------------------------------------------------------
  eld_n <- meanall(eld_n10)

  ## mhl_n test {{{-------------------------------------------------------------
  mhl_n <- meanall(mhl_n10)

  ## mhl_p test {{{-------------------------------------------------------------
  
  mhl_p75 <- try(meanall(mhl_p075))
  
  mhl_p80 <- try(meanall(mhl_p080))
  
  mhl_p85 <- try(meanall(mhl_p085))
  
  mhl_p90 <- try(meanall(mhl_p090))
  
  mhl_p95 <- try(meanall(mhl_p095))
  ## for the large simulation we used test_mhl_p09
  # mhl_p <- meanall(test_mhl_p09)
  
  ## sgl_n test {{{-------------------------------------------------------------
  sgl_n <- meanall(sgl_n10)


  if (exists("lmm_test")) {
    lmm <- list()
    lmm$bias <-  lmm_test %>%
      transmute(bias = abs(pred - ht)) %>%
      unlist() %>%
      mean()
    lmm$mse <-  lmm_test %>%
      transmute(mse = (pred - ht)^2) %>%
      unlist() %>%
      mean() 
    ## rmse is the sqrt
    lmm$cov50<- lmm_test %>%
      transmute(ifelse(ht >= centile25 & ht <= centile75, 1, 0)) %>%
      unlist() %>%
      mean()
    lmm$cov80<- lmm_test %>%
      transmute(ifelse(ht >= centile10 & ht <= centile90, 1, 0)) %>%
      unlist() %>%
      mean()
    lmm$cov90<- lmm_test %>%
      transmute(ifelse(ht >= centile05 & ht <= centile95, 1, 0)) %>%
      unlist() %>%
      mean()
  } else {
    lmm = NULL
  }

  return(list(eld_n = eld_n,
              mhl_n = mhl_n,
              mhl_p75 = mhl_p75,
              mhl_p80 = mhl_p80,
              mhl_p85 = mhl_p85,
              mhl_p90 = mhl_p90,
              mhl_p95 = mhl_p95,
              sgl_n = sgl_n,
              lmm = lmm))
}


```


```{r}
## remember to add the / at the end of the location /

## there are two setup for simulation 
##  L simulation with 900 individuals ------------------
##  S simulation with 500 individuals -----------------
## with 400 for training set; 100 for testing set
folder1 <- "result_ss500_simulation"

## for each simulation sample size (large or small)
## each has three setup with different anchor time set
## 3 anchor time setting for (6, 9, 12)
## 4 anchor time setting for (3, 6, 9, 12)
## 6 anchor time setting for (3, 6, 9, 12, 13, 15)
# folder2 <- "sim1000_ss500_anchor3time"
# folder2 <- "sim1000_ss500_anchor4time"
folder2 <- "sim1000_ss500_anchor6time"

# file_location <- paste0("results/", folder1, "/", folder2, "/")
# files <- list.files(path = file_location, pattern = ".Rdata")
# ## pull out the simulation results from the folder each as a list of
# ## bias, rmse, coverage50, coverage80, and coverage90
# sim_ss <- map_dfr(files, ~pull_simulation(file_location, .),
#                      .progress = list(type = "iterator",
#                                       format = "Calculating {cli::pb_bar} {cli::pb_percent}",
#                                       clear = TRUE))
# sim_ss <- sim_ss %>%
#   mutate(term = rep(c("bias", "mse", "coverage50", "coverage80", "coverage90"), length(files)))
# save(sim_ss, file = paste0("data/S06_", folder2, "_0summary_", Sys.Date(), ".Rdata"))

```


```{r}
## There will be three Rdata files saved in the data folder 
#
# load(paste0("data/S06_", folder2, "_0summary_", Sys.Date(), ".Rdata"))
load("~/Desktop/paper2023/data/S06_sim1000_ss500_anchor3time_0summary_2023-08-31.Rdata")
data <- sim_ss500 %>%
  pivot_longer(cols = -term,
               names_to = "method",
               values_to = "values") %>%
  mutate(method = factor(method, levels = c("sgl_n", "eld_n", "mhl_n", 
                                            "mhl_p75", "mhl_p80", "mhl_p85",
                                            "mhl_p90", "mhl_p95", "lmm")))

library(latex2exp)
bias_plot <- data %>%
  filter(term == "bias") %>%
  ggplot(aes(x = method, y = as.numeric(values), group = factor(method))) +
  scale_x_discrete(labels = c("sgl_n" = parse(text = latex2exp::TeX("$S_{\\kappa = 10}$")),
                              "eld_n" = parse(text = latex2exp::TeX("$E_{\\kappa = 10}$")),
                              "mhl_n" = parse(text = latex2exp::TeX("$M_{\\kappa = 10}$")),
                              "mhl_p75" = parse(text = latex2exp::TeX("$M_{\\alpha = 0.75}$")),
                              "mhl_p80" = parse(text = latex2exp::TeX("$M_{\\alpha = 0.80}$")),
                              "mhl_p85" = parse(text = latex2exp::TeX("$M_{\\alpha = 0.85}$")),
                              "mhl_p90" = parse(text = latex2exp::TeX("$M_{\\alpha = 0.90}$")),
                              "mhl_p95" = parse(text = latex2exp::TeX("$M_{\\alpha = 0.95}$")),
                              "lmm" = "LMM")) +
  geom_point(aes(color = method)) +
  geom_boxplot(aes(fill = method)) +
  theme_bw() +
  labs(x = NULL) +
  labs(y = "Bias") +
  ggthemes::scale_fill_tableau("Jewel Bright") + 
  ## so far the best color composition
  ggthemes::scale_colour_tableau("Jewel Bright") +
  ## facet_wrap("group") +
  theme(legend.position = "none") +

  theme(axis.text.x = element_text(size = 15),
        axis.text.y = element_text(size = 15),
        axis.title.y = element_text(size = 16)) +
  ylim(c(1.5, 2.3))
bias_plot


```




```{r}
rmse_plot <- data %>%
  filter(term == "mse") %>% 
  mutate(values = sqrt(as.numeric(values))) %>%
  ggplot(aes(x = method, y = as.numeric(values), group = method)) +
  geom_point(aes(color = method)) +
  geom_boxplot(aes(fill = method)) +
  theme_bw() +
  labs(x = NULL) +
  labs(y = "RMSE") +
  ggthemes::scale_fill_tableau("Jewel Bright") + 
  ## so far the best color composition
  ggthemes::scale_colour_tableau("Jewel Bright") +
  ## facet_wrap("group") +
  theme(legend.position = "none") +
  scale_x_discrete(labels = c("sgl_n" = parse(text = latex2exp::TeX("$S_{\\kappa = 10}$")),
                              "eld_n" = parse(text = latex2exp::TeX("$E_{\\kappa = 10}$")),
                              "mhl_n" = parse(text = latex2exp::TeX("$M_{\\kappa = 10}$")),
                              "mhl_p75" = parse(text = latex2exp::TeX("$M_{\\alpha = 0.75}$")),
                              "mhl_p80" = parse(text = latex2exp::TeX("$M_{\\alpha = 0.80}$")),
                              "mhl_p85" = parse(text = latex2exp::TeX("$M_{\\alpha = 0.85}$")),
                              "mhl_p90" = parse(text = latex2exp::TeX("$M_{\\alpha = 0.90}$")),
                              "mhl_p95" = parse(text = latex2exp::TeX("$M_{\\alpha = 0.95}$")),
                              "lmm" = "LMM")) +
  theme(axis.text.x = element_text(size = 15),
        axis.text.y = element_text(size = 15),
        axis.title.y = element_text(size = 16)) +
  ylim(c(2, 4))
rmse_plot
```


```{r}
cov50_plot <- data %>% 
  filter(term == "coverage50") %>% 
  ggplot(aes(x = method, y = as.numeric(values)),
         group = method) +
  geom_point(aes(color = method)) +
  geom_boxplot(aes(fill = method)) +
  theme_bw() +
  labs(x = NULL) +
  labs(y = "50% CR") +
  ggthemes::scale_fill_tableau("Jewel Bright") + 
  ## so far the best color composition
  ggthemes::scale_colour_tableau("Jewel Bright") +
  ## facet_wrap("group") +
  theme(legend.position = "none") +
  scale_x_discrete(labels = c("sgl_n" = parse(text = latex2exp::TeX("$S_{\\kappa = 10}$")),
                              "eld_n" = parse(text = latex2exp::TeX("$E_{\\kappa = 10}$")),
                              "mhl_n" = parse(text = latex2exp::TeX("$M_{\\kappa = 10}$")),
                              "mhl_p75" = parse(text = latex2exp::TeX("$M_{\\alpha = 0.75}$")),
                              "mhl_p80" = parse(text = latex2exp::TeX("$M_{\\alpha = 0.80}$")),
                              "mhl_p85" = parse(text = latex2exp::TeX("$M_{\\alpha = 0.85}$")),
                              "mhl_p90" = parse(text = latex2exp::TeX("$M_{\\alpha = 0.90}$")),
                              "mhl_p95" = parse(text = latex2exp::TeX("$M_{\\alpha = 0.95}$")),
                              "lmm" = "LMM")) +
  theme(axis.text.x = element_text(size = 15),
        axis.text.y = element_text(size = 15),
        axis.title.y = element_text(size = 16)) 

## the tableau is in the ggthemes
cov50_plot
```



```{r}
cov80_plot <- data %>% 
          filter(term == "coverage80") %>%
          ggplot(aes(x = method, y = as.numeric(values)),
                 group = method) +
          geom_point(aes(color = method)) +
          geom_boxplot(aes(fill = method)) +
          theme_bw() +
         labs(x = NULL) +
          labs(y = "80% CR") +
          ggthemes::scale_fill_tableau("Jewel Bright") + 
          ## so far the best color composition
          ggthemes::scale_colour_tableau("Jewel Bright") +
          ## facet_wrap("group") +
          theme(legend.position = "none") +
  scale_x_discrete(labels = c("sgl_n" = parse(text = latex2exp::TeX("$S_{\\kappa = 10}$")),
                              "eld_n" = parse(text = latex2exp::TeX("$E_{\\kappa = 10}$")),
                              "mhl_n" = parse(text = latex2exp::TeX("$M_{\\kappa = 10}$")),
                              "mhl_p75" = parse(text = latex2exp::TeX("$M_{\\alpha = 0.75}$")),
                              "mhl_p80" = parse(text = latex2exp::TeX("$M_{\\alpha = 0.80}$")),
                              "mhl_p85" = parse(text = latex2exp::TeX("$M_{\\alpha = 0.85}$")),
                              "mhl_p90" = parse(text = latex2exp::TeX("$M_{\\alpha = 0.90}$")),
                              "mhl_p95" = parse(text = latex2exp::TeX("$M_{\\alpha = 0.95}$")),
                              "lmm" = "LMM")) +
  theme(axis.text.x = element_text(size = 15),
        axis.text.y = element_text(size = 15),
        axis.title.y = element_text(size = 16)) 
          ## the tableau is in the ggthemes
cov80_plot
```


```{r}
cov90_plot <- data %>% 
          filter(term == "coverage90") %>%
          ggplot(aes(x = method, y = as.numeric(values)),
                 group = method) +
          geom_point(aes(color = method)) +
          geom_boxplot(aes(fill = method)) +
          theme_bw() +
          labs(x = NULL) +
          labs(y = "90% CR") +
          ggthemes::scale_fill_tableau("Jewel Bright") + 
          ## so far the best color composition
          ggthemes::scale_colour_tableau("Jewel Bright") +
          ## facet_wrap("group") +
          theme(legend.position = "none") +
  scale_x_discrete(labels = c("sgl_n" = parse(text = latex2exp::TeX("$S_{\\kappa = 10}$")),
                              "eld_n" = parse(text = latex2exp::TeX("$E_{\\kappa = 10}$")),
                              "mhl_n" = parse(text = latex2exp::TeX("$M_{\\kappa = 10}$")),
                              "mhl_p75" = parse(text = latex2exp::TeX("$M_{\\alpha = 0.75}$")),
                              "mhl_p80" = parse(text = latex2exp::TeX("$M_{\\alpha = 0.80}$")),
                              "mhl_p85" = parse(text = latex2exp::TeX("$M_{\\alpha = 0.85}$")),
                              "mhl_p90" = parse(text = latex2exp::TeX("$M_{\\alpha = 0.90}$")),
                              "mhl_p95" = parse(text = latex2exp::TeX("$M_{\\alpha = 0.95}$")),
                              "lmm" = "LMM")) +
  theme(axis.text.x = element_text(size = 15),
        axis.text.y = element_text(size = 15),
        axis.title.y = element_text(size = 16)) 
          ## the tableau is in the ggthemes
cov90_plot
```


```{r fig.width=10, fig.height=3, warning=FALSE}
bias_plot
ggsave(paste0("figure/S06_", folder2, "_1bias_", Sys.Date(), ".png"))
rmse_plot
ggsave(paste0("figure/S06_", folder2, "_2rmse_", Sys.Date(), ".png"))
cov50_plot + 
  geom_hline(yintercept = 0.5, linetype="dashed", color = "indianred")
ggsave(paste0("figure/S06_", folder2, "_3cov50_", Sys.Date(), ".png"))
cov80_plot +
  geom_hline(yintercept = 0.8, linetype="dashed", color = "indianred")
ggsave(paste0("figure/S06_", folder2, "_4cov80_", Sys.Date(), ".png"))
cov90_plot +
  geom_hline(yintercept = 0.9, linetype="dashed", color = "indianred")
ggsave(paste0("figure/S06_", folder2, "_5cov90_", Sys.Date(), ".png"))

```


```{r, fig.height= 10, fig.width=10}
library(ggpubr)
figure1 <- ggarrange(bias_plot, 
                    # + theme(axis.text.x=element_blank()),
                    rmse_plot,
                    # + theme(axis.text.x=element_blank()),
                    # cov50_plot,
                    # + theme(axis.text.x=element_blank()), 
                    cov90_plot +
                      geom_hline(yintercept = 0.9,
                                 linetype = "dashed", 
                                 color = "indianred"),
                    # + theme(axis.text.x=element_blank()),
                    ncol = 1, nrow = 3)

figure1
ggsave(paste0("figure/S06_", folder2, "_6combine_", Sys.Date(), ".png"))
```


```{r, fig.height= 10, fig.width=10}
figure2 <- ggarrange(bias_plot, 
                    # + theme(axis.text.x=element_blank()),
                    rmse_plot,
                    # + theme(axis.text.x=element_blank()),
                    cov50_plot +
                      geom_hline(yintercept = 0.5,
                                 linetype = "dashed", 
                                 color = "indianred"),
                    cov80_plot +
                      geom_hline(yintercept = 0.8,
                                 linetype = "dashed", 
                                 color = "indianred"),
                    # + theme(axis.text.x=element_blank()), 
                    cov90_plot +
                      geom_hline(yintercept = 0.9,
                                 linetype = "dashed", 
                                 color = "indianred"),
                    # + theme(axis.text.x=element_blank()),
                    ncol = 1, nrow = 5)

figure2
ggsave(paste0("figure/S06_", folder2, "_7all_", Sys.Date(), ".png"))
```


```{r, fig.height= 10, fig.width=10}
figure3 <- ggarrange(#bias_plot, 
                    # + theme(axis.text.x=element_blank()),
                    #rmse_plot,
                    # + theme(axis.text.x=element_blank()),
                    cov50_plot +
                      geom_hline(yintercept = 0.5,
                                 linetype = "dashed", 
                                 color = "indianred"),
                    cov80_plot +
                      geom_hline(yintercept = 0.8,
                                 linetype = "dashed", 
                                 color = "indianred"),
                    # + theme(axis.text.x=element_blank()), 
                    cov90_plot +
                      geom_hline(yintercept = 0.9,
                                 linetype = "dashed", 
                                 color = "indianred"),
                    # + theme(axis.text.x=element_blank()),
                    ncol = 1, nrow = 3)

figure3
ggsave(paste0("figure/S06_", folder2, "_8cr_", Sys.Date(), ".png"))
```

```{r}
sessionInfo()
```

