---
title: "08_figure5_supp_chi_square"
author: "randy"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      warnings = FALSE,
                      message = FALSE,
                      comment = "#>",
                      #results = "hide",
                      digits = 4,
                      error = FALSE)

## clean the R environment
graphics.off()
rm(list = ls())
freshr::freshr()

## load packages
library(here, quietly = TRUE)
library(tidyverse, quietly = TRUE)
library(gtsummary, quietly = TRUE)
library(flextable, quietly = TRUE)

## check the directory for the file
# here::dr_here()
here::set_here()

## the figure or results should be saved 
# paste0("foldername/Sfilename_workingresult_", 
#.       Sys.Date(), ".filetype")
```


```{r}
x <- seq(0, 10, length.out = 200)
chi <- map_dfc(c(1, 2, 3, 4, 5, 6), ~dchisq(x, df = .)) %>%
  dplyr::select(`1` = 1, `2` = 2, `3` = 3, `4` = 4,
                `5` = 5, `6` = 6) %>%
  mutate(x = x)

chi2 <- chi %>%
  pivot_longer(-x, 
               names_to = "df",
               values_to = "density") %>%
  mutate(df = factor(df, levels = c(1, 2, 3, 4, 5, 6))) %>%
  ggplot(aes(x, y = density, color = df)) +
  geom_line(linewidth = 1) +
  ylim(c(0, 0.45)) +
  labs(x = NULL, 
       y = "Density", 
       color = "Df") +
  theme_bw() +
  theme(axis.text.x = element_text(size = 15),
        axis.text.y = element_text(size = 15),
        axis.title.y = element_text(size = 16),
        legend.position = c(0.8, 0.6),
        legend.title = element_text(size = 16),
        legend.text = element_text(size = 15)) +
  ggthemes::scale_colour_tableau("Jewel Bright") 
chi2
```


```{r}
chi1 <- chi %>%
  ggplot() +
  geom_line(aes(x, y = `1`),
            color = "#EB1e2c",
            alpha = 0.8,
            linewidth = 1) +
  geom_ribbon(data = chi[chi$x > qchisq(0.85, 1, lower.tail = F), ],
              aes(x, ymin = 0, ymax = `1`),
              alpha = 0.1, 
              fill = "#EB1e2c") +
  geom_line(aes(x, y = `4`),
            color = "gold2",
            linewidth = 1) +
  geom_ribbon(data = chi[chi$x > qchisq(0.85, 4, lower.tail = F), ],
              aes(x, ymin = 0, ymax = `4`),
              alpha = 0.4, 
              fill = "gold2") +
  geom_line(aes(x, y = `6`),
            color = "#64cdcc",
            linewidth = 1) +
  ylim(c(0, 0.45)) + 
  geom_ribbon(data = chi[chi$x > qchisq(0.85, 6, lower.tail = F), ],
              aes(x, ymin = 0, ymax = `6`),
              alpha = 0.4, 
              fill = "#64cdcc") +
  
  labs(x = NULL, 
       y = "Density", 
       color = "Df") +
  theme_bw() +
  theme(axis.text.x = element_text(size = 15),
        axis.text.y = element_text(size = 15),
        axis.title.y = element_text(size = 16),
        legend.position = c(0.9, 0.6),
        legend.title = element_text(size = 16),
        legend.text = element_text(size = 15)) 
chi1
```


```{r fig.height=4, fig.width=10}
library(ggpubr)
figure1 <- ggarrange(chi2, chi1,
                    ncol = 2, nrow = 1)

figure1
ggsave(paste0("figure/S08_supp_figure_chi_square", Sys.Date(), ".png"))
```

